# Generated by Django 5.1.4 on 2025-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                (
                    "about",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("NON IT", "NON IT"),
                            ("MOBILE PHONES", "MOBILE PHONES"),
                        ],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
