# Generated by Django 5.1.4 on 2025-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="company",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("NON IT", "NON IT"),
                    ("MOBILE PHONES", "MOBILE PHONES"),
                ],
                default="IT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.CharField(max_length=100),
        ),
    ]
