# Generated by Django 5.1.4 on 2025-01-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_company_active_company_category_alter_company_about"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="category",
            new_name="type",
        ),
    ]
