# Generated by Django 5.1.4 on 2025-01-11 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_category_company_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="type",
            new_name="company_type",
        ),
    ]
