# Generated by Django 5.1.4 on 2025-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_type_company_company_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="company",
            name="company_type",
        ),
        migrations.AddField(
            model_name="company",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="industry_type",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("Non IT", "Non IT"),
                    ("Mobile Phones", "Mobile Phones"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(),
        ),
    ]
