# Generated by Django 5.1.4 on 2025-01-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_company_company_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry_type",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("Non IT", "Non IT"),
                    ("Mobile Phone", "Mobile Phone"),
                ],
                max_length=100,
            ),
        ),
    ]