# Generated by Django 5.1.4 on 2025-01-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="Company",
        ),
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=11),
        ),
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.company"
            ),
        ),
    ]
